#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Xunjin MH10 Modbus 协议 Python 绑定。

本文件是 `include/mh10_protocol.h` 的 Python 等价物，用于虚拟测试、
仿真器和协议文档示例。所有常量与 C 头文件保持严格一致。
"""

# 协议版本
MH10_PROTOCOL_VERSION_MAJOR = 1
MH10_PROTOCOL_VERSION_MINOR = 1
MH10_PROTOCOL_VERSION_PATCH = 0
MH10_PROTOCOL_VERSION = (MH10_PROTOCOL_VERSION_MAJOR << 8) | \
                        (MH10_PROTOCOL_VERSION_MINOR << 4)  | \
                        MH10_PROTOCOL_VERSION_PATCH

# Modbus 物理层参数
MH10_MODBUS_BAUDRATE = 115200
MH10_MODBUS_DATA_BITS = 8
MH10_MODBUS_PARITY = 'N'
MH10_MODBUS_STOP_BITS = 1
MH10_MODBUS_DEFAULT_TIMEOUT_MS = 100
MH10_MODBUS_DEFAULT_RETRIES = 2

# 在线检测与复位魔数
MH10_MODBUS_ONLINE_CONST = 0xA0A0
MH10_MODBUS_REBOOT_MAGIC = 0x5A5A

# 从机地址
MH10_SLAVE_ID_BROADCAST = 0x00
MH10_SLAVE_ID_MOTOR = 0x01
MH10_SLAVE_ID_FRONT_BOARD = 0x02
MH10_SLAVE_ID_BACK_BOARD = 0x03
MH10_SLAVE_ID_ATTACH_MOTOR = 0x04

# 功能码
MH10_MB_FC_READ_HOLDING_REGISTERS = 0x03
MH10_MB_FC_WRITE_SINGLE_REGISTER = 0x06
MH10_MB_FC_WRITE_MULTIPLE_REGISTERS = 0x10

# 系统公共寄存器
MH10_MB_REG_CONST = 0x18
MH10_MB_REG_REBOOT = 0x19
MH10_MB_REG_HW_VERSION = 0x1A
MH10_MB_REG_SW_VERSION = 0x1B
MH10_MB_REG_SVN_NUM = 0x1C
MH10_MB_REG_PROTOCOL_VERSION = 0x1D
MH10_MB_REG_RESERVED_1E = 0x1E
MH10_MB_REG_RESERVED_1F = 0x1F

# 前板寄存器
MH10_MB_FO_TOOLHEAD_STATE_RO = 0x00
MH10_MB_FO_TOOLHEAD_EXCEPTION_RW = 0x01
MH10_MB_FO_TOOLHEAD_INFO_RO = 0x02
MH10_MB_FO_TOOLHEAD_SPEED_RO = 0x03
MH10_MB_FO_TOOLHEAD_COUNT_RO = 0x04
MH10_MB_FO_TOOLHEAD_POS_RO = 0x05
MH10_MB_FO_PEDAL_INSERT_RO = 0x06
MH10_MB_FO_PEDAL_SWITCH_RO = 0x07
MH10_MB_FO_TOOLHEAD_INSERT_RO = 0x08
MH10_MB_FO_TOOLHEAD_SWITCH_RO = 0x09
MH10_MB_FO_TOOLHEAD_STATE_RW = 0x0A
MH10_MB_FO_TOOLHEAD_TARGET_SPEED_RW = 0x0B
MH10_MB_FO_TOOLHEAD_TARGET_DIR_RW = 0x0C
MH10_MB_FO_TOOLHEAD_READY_TO_SELFCHECK_WO = 0x0D
MH10_MB_FO_TOOLHEAD_READY_TO_START_WO = 0x0E
MH10_MB_FO_TOOLHEAD_PEDAL_DELAY_WO = 0x0F
MH10_MB_FO_TOOLHEAD_CYCLE_COUNTS_RW = 0x10

# 后板寄存器
MH10_MB_BK_VERSION_RO = 0x00
MH10_MB_BK_NP_IS_RO = 0x01
MH10_MB_BK_NP_OS_RO = 0x02
MH10_MB_BK_TARGET_STATE_WO = 0x03

# 前板状态枚举
MH10_TOOLHEAD_STATE_OFFLINE = 0
MH10_TOOLHEAD_STATE_PEDAL_ONLY = 1
MH10_TOOLHEAD_STATE_TOOLHEAD_ONLY = 2
MH10_TOOLHEAD_STATE_ONLINE_WAIT_SELFCHECK = 3
MH10_TOOLHEAD_STATE_SELF_CHECK = 4
MH10_TOOLHEAD_STATE_ONLINE_READY = 5
MH10_TOOLHEAD_STATE_WAITTING = 6
MH10_TOOLHEAD_STATE_RUNNING = 7
MH10_TOOLHEAD_STATE_ATTRACTING = 8
MH10_TOOLHEAD_STATE_EXCEPTION = 9

# 异常码
MH10_TOOLHEAD_EXP_NONE = 0
MH10_TOOLHEAD_EXP_READ_CARD = 1
MH10_TOOLHEAD_EXP_TOOLHEAD_OFFLINE = 2
MH10_TOOLHEAD_EXP_TOOLHEAD_SWITCH = 3
MH10_TOOLHEAD_EXP_PEDAL_OFFLINE = 4
MH10_TOOLHEAD_EXP_MOTOR_STOP = 5
MH10_TOOLHEAD_EXP_MOTOR_SPEED = 6
MH10_TOOLHEAD_EXP_MOTOR_DIR = 7

# 后板状态
MH10_BACKBOARD_STATE_CALIBRATION = 0
MH10_BACKBOARD_STATE_CLOSED = 1
MH10_BACKBOARD_STATE_OPEN = 2

# 自检/运行确认
MH10_SELFCHECK_NOT_READY = 0
MH10_SELFCHECK_READY = 1
MH10_SELFCHECK_SKIP = 2
MH10_RUN_NOT_READY = 0
MH10_RUN_READY = 1
MH10_ATTACH_READY = 2

# 缩放因子
MH10_NP_SCALE_FACTOR = -100.0
MH10_TOOLHEAD_SPEED_SCALE = 100


class MH10RegisterMap:
    """提供寄存器地址到名称的反向查找，便于测试日志输出。"""

    _SYSTEM = {
        MH10_MB_REG_CONST: "MB_REG_CONST",
        MH10_MB_REG_REBOOT: "MB_REG_REBOOT",
        MH10_MB_REG_HW_VERSION: "MB_REG_HW_VERSION",
        MH10_MB_REG_SW_VERSION: "MB_REG_SW_VERSION",
        MH10_MB_REG_SVN_NUM: "MB_REG_SVN_NUM",
        MH10_MB_REG_PROTOCOL_VERSION: "MB_REG_PROTOCOL_VERSION",
    }

    _FRONT = {
        MH10_MB_FO_TOOLHEAD_STATE_RO: "MB_FO_TOOLHEAD_STATE_RO",
        MH10_MB_FO_TOOLHEAD_EXCEPTION_RW: "MB_FO_TOOLHEAD_EXCEPTION_RW",
        MH10_MB_FO_TOOLHEAD_INFO_RO: "MB_FO_TOOLHEAD_INFO_RO",
        MH10_MB_FO_TOOLHEAD_SPEED_RO: "MB_FO_TOOLHEAD_SPEED_RO",
        MH10_MB_FO_TOOLHEAD_COUNT_RO: "MB_FO_TOOLHEAD_COUNT_RO",
        MH10_MB_FO_TOOLHEAD_POS_RO: "MB_FO_TOOLHEAD_POS_RO",
        MH10_MB_FO_PEDAL_INSERT_RO: "MB_FO_PEDAL_INSERT_RO",
        MH10_MB_FO_PEDAL_SWITCH_RO: "MB_FO_PEDAL_SWITCH_RO",
        MH10_MB_FO_TOOLHEAD_INSERT_RO: "MB_FO_TOOLHEAD_INSERT_RO",
        MH10_MB_FO_TOOLHEAD_SWITCH_RO: "MB_FO_TOOLHEAD_SWITCH_RO",
        MH10_MB_FO_TOOLHEAD_STATE_RW: "MB_FO_TOOLHEAD_STATE_RW",
        MH10_MB_FO_TOOLHEAD_TARGET_SPEED_RW: "MB_FO_TOOLHEAD_TARGET_SPEED_RW",
        MH10_MB_FO_TOOLHEAD_TARGET_DIR_RW: "MB_FO_TOOLHEAD_TARGET_DIR_RW",
        MH10_MB_FO_TOOLHEAD_READY_TO_SELFCHECK_WO: "MB_FO_TOOLHEAD_READY_TO_SELFCHECK_WO",
        MH10_MB_FO_TOOLHEAD_READY_TO_START_WO: "MB_FO_TOOLHEAD_READY_TO_START_WO",
        MH10_MB_FO_TOOLHEAD_PEDAL_DELAY_WO: "MB_FO_TOOLHEAD_PEDAL_DELAY_WO",
        MH10_MB_FO_TOOLHEAD_CYCLE_COUNTS_RW: "MB_FO_TOOLHEAD_CYCLE_COUNTS_RW",
    }

    _BACK = {
        MH10_MB_BK_VERSION_RO: "MB_BK_VERSION_RO",
        MH10_MB_BK_NP_IS_RO: "MB_BK_NP_IS_RO",
        MH10_MB_BK_NP_OS_RO: "MB_BK_NP_OS_RO",
        MH10_MB_BK_TARGET_STATE_WO: "MB_BK_TARGET_STATE_WO",
    }

    @classmethod
    def name(cls, slave_id: int, address: int) -> str:
        if slave_id == MH10_SLAVE_ID_FRONT_BOARD:
            return cls._FRONT.get(address, f"REG_0x{address:02X}")
        if slave_id == MH10_SLAVE_ID_BACK_BOARD:
            return cls._BACK.get(address, f"REG_0x{address:02X}")
        return cls._SYSTEM.get(address, f"REG_0x{address:02X}")
